################ English language ##################
[ca]
languageCode = 'ca'
languageName = 'va'
title = 'Mercat de Productors a Orba - Mans de la Terra'
weight = 1
[es]
languageCode = 'es'
languageName = 'es'
title = 'Mercado de Productores en Orba - Mans de la Terra'
weight = 2
[en]
languageCode = 'en-US'
languageName = 'en'
title = 'Local Producers Market in Orba - Mans de la Terra'
weight = 3
