############# English navigation ##############

# main menu
[[main]]
name = "Market"
url = "/"
weight = 1

[[main]]
name = "How to get here"
url = "/directions"
weight = 2

# footer menu
[[footer]]
name = "Who we are"
url = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy"
weight = 2
